/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const InventoryLazyImport = createFileRoute('/inventory')()
const AddMaterialLazyImport = createFileRoute('/add-material')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const InventoryLazyRoute = InventoryLazyImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/inventory.lazy').then((d) => d.Route))

const AddMaterialLazyRoute = AddMaterialLazyImport.update({
  id: '/add-material',
  path: '/add-material',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/add-material.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/add-material': {
      id: '/add-material'
      path: '/add-material'
      fullPath: '/add-material'
      preLoaderRoute: typeof AddMaterialLazyImport
      parentRoute: typeof rootRoute
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/add-material': typeof AddMaterialLazyRoute
  '/inventory': typeof InventoryLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/add-material': typeof AddMaterialLazyRoute
  '/inventory': typeof InventoryLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/add-material': typeof AddMaterialLazyRoute
  '/inventory': typeof InventoryLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-material' | '/inventory'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-material' | '/inventory'
  id: '__root__' | '/' | '/add-material' | '/inventory'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AddMaterialLazyRoute: typeof AddMaterialLazyRoute
  InventoryLazyRoute: typeof InventoryLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AddMaterialLazyRoute: AddMaterialLazyRoute,
  InventoryLazyRoute: InventoryLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/add-material",
        "/inventory"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/add-material": {
      "filePath": "add-material.lazy.jsx"
    },
    "/inventory": {
      "filePath": "inventory.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
